# Generate-Documentation.ps1
# PowerShell script to automatically generate project documentation
# This script is called during Release build post-build events

param(
    [string]$ProjectPath = (Get-Location),
    [string]$Configuration = "Release",
    [switch]$Verbose
)

# Colors for output
$InfoColor = "Cyan"
$SuccessColor = "Green"
$ErrorColor = "Red"
$WarningColor = "Yellow"

function Write-Info {
    param([string]$Message)
    Write-Host "[INFO] $Message" -ForegroundColor $InfoColor
}

function Write-Success {
    param([string]$Message)
    Write-Host "[SUCCESS] $Message" -ForegroundColor $SuccessColor
}

function Write-Error-Custom {
    param([string]$Message)
    Write-Host "[ERROR] $Message" -ForegroundColor $ErrorColor
}

function Write-Warning-Custom {
    param([string]$Message)
    Write-Host "[WARNING] $Message" -ForegroundColor $WarningColor
}

Write-Info "================================"
Write-Info "Documentation Generation Script"
Write-Info "================================"

# Check if we're in Release configuration
if ($Configuration -ne "Release") {
    Write-Warning-Custom "Skipping documentation generation for $Configuration configuration"
    Write-Info "Documentation is only generated during Release builds"
    exit 0
}

Write-Info "Configuration: $Configuration"
Write-Info "Project Path: $ProjectPath"

# Step 1: Check if DocFX is installed
Write-Info "Step 1: Checking DocFX installation..."
try {
    $docfxVersion = docfx --version 2>&1
    Write-Success "DocFX is installed: $docfxVersion"
} catch {
    Write-Error-Custom "DocFX is not installed"
    Write-Info "Installing DocFX..."
    dotnet tool install -g docfx
    if ($LASTEXITCODE -eq 0) {
        Write-Success "DocFX installed successfully"
    } else {
        Write-Error-Custom "Failed to install DocFX"
        exit 1
    }
}

# Step 2: Check if docfx.json exists
Write-Info "Step 2: Checking docfx.json configuration..."
$docfxJsonPath = Join-Path $ProjectPath "docfx.json"
if (-Not (Test-Path $docfxJsonPath)) {
    Write-Error-Custom "docfx.json not found at $docfxJsonPath"
    exit 1
}
Write-Success "Found docfx.json"

# Step 3: Generate API documentation
Write-Info "Step 3: Generating API documentation..."
try {
    Push-Location $ProjectPath
    docfx docfx.json
    if ($LASTEXITCODE -eq 0) {
        Write-Success "API documentation generated successfully"
    } else {
        Write-Error-Custom "Failed to generate API documentation"
        Pop-Location
        exit 1
    }
    Pop-Location
} catch {
    Write-Error-Custom "Error during API documentation generation: $_"
    Pop-Location
    exit 1
}

# Step 4: Copy generated documentation
Write-Info "Step 4: Organizing generated documentation..."
$docsSrcPath = Join-Path $ProjectPath "_site"
$docsDestPath = Join-Path $ProjectPath "docs"

if (Test-Path $docsSrcPath) {
    if (Test-Path $docsDestPath) {
        Remove-Item $docsDestPath -Recurse -Force
    }
    Copy-Item $docsSrcPath $docsDestPath -Recurse
    Write-Success "Documentation copied to docs folder"
} else {
    Write-Warning-Custom "Generated documentation path not found: $docsSrcPath"
}

# Step 5: Generate README for docs
Write-Info "Step 5: Creating documentation index..."
$docReadmePath = Join-Path $docsDestPath "README.md"

$docReadmeContent = @"
# PlayGround App - Documentation

Auto-generated documentation for the PlayGround App project.

**Generated**: $(Get-Date -Format "yyyy-MM-dd HH:mm:ss UTC")

## Contents

- **API Documentation** - Complete API reference for all classes and methods
- **Code Documentation** - Architecture, design patterns, and implementation details
- **Setup Guide** - Installation and setup instructions

## Quick Links

- [Main README](../README.md)
- [Code Documentation](../CODE_DOCUMENTATION.md)
- [API Reference](./api/index.html)

## Generated By

- Tool: DocFX
- Configuration: docfx.json
- .NET Version: 10.0

---

This documentation is automatically generated during Release builds.
"@

if (Test-Path $docsDestPath) {
    Set-Content -Path $docReadmePath -Value $docReadmeContent -Encoding UTF8
    Write-Success "Documentation index created"
}

# Step 6: Summary
Write-Info "Step 6: Summary..."
Write-Success "================================"
Write-Success "Documentation Generation Complete!"
Write-Success "================================"
Write-Info "Documentation location: $docsDestPath"
Write-Info "Generated files:"
Get-ChildItem $docsDestPath -Recurse | Where-Object { $_.PSIsContainer -eq $false } | ForEach-Object {
    Write-Info "  - $($_.Name)"
}

Write-Success "Documentation is ready for publishing"
exit 0
